#!/usr/bin/python

import spidev
import time
import os

delay = 0.5
moisture_channel = 0

spi = spidev.SpiDev()
spi.open(0,0)
spi.max_speed_hz=1000000

def readadc(adcnum): 
	r = spi.xfer2([1, (8+adcnum)<<4, 0])
	data = ((r[1] & 3) << 8) + r[2]
	return data
 
moisture_value = readadc(moisture_channel)
print moisture_value


